spring:
  application:
    name : demo9
  datasource:
    url: jdbc:mariadb://192.168.216.24/site
    username: hgy
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql : debug

